### ISSUE TITLE
Return old file

### ISSUE THREAD

**Issue by JasonSorria** [kevinhwang91/rnvimr#10]
If I have opened a new file by Ranger, how to return the old file?

**Comment by kevinhwang91** [comment]
Press `q` will hide the ranger's window and enable `attach file`. If you want to return the file selected previously, you can invoke `call rnvimr#rpc#disable_attach_file()` before executing `:RnvimrToggle` in neovim or executing `:RnvimrToggle` in ranger instead of Pressing `q`.

Note: `let g:rnvimr_pick_enable=1` will automatically enable `attach file`.
