### ISSUE TITLE
Using/migrating rnvimr for other file managers?

### ISSUE THREAD

**Issue by mostafaqanbaryan** [kevinhwang91/rnvimr#158]
First of all, Thank you for this great plugin.
This plugin is really awesome and I'm so addicted to it that cannot change my default editor anymore.
But as you might know, there are some other (_faster_) file managers other than `ranger`.
There are some good plugins like `is0n/fm-nvim` that support many editors, but after using `rnvimr`, the lack of features (_rpc_ like) is killing me.
So I wanted to know, is there any plan for migrating to any other file managers or its possible at all?
(I know that you're doing a lot of things in `python` on `ranger` side, but I don't know if it's possible on other file managers)

**Comment by kevinhwang91** [comment]
No plan. The performance of ranger is poor, but it's sufficient for me. Even though others have better performance, they are still in development, and I actually have no time to create the file manager plugin for them.

However, I believe the authors of the file manager will develop the nvim plugin because nvim is popular, and this plugin will inspire them.
