### ISSUE TITLE
Just a big thanks for this plugin !

### ISSUE THREAD

**Issue by m040601** [kevinhwang91/rnvimr#27]
Thank you for your work in this plugin.
It does work wonderfully and seems very polished.
Neovim's floating window capabilities are in fact surprisingly usefull.

At first I was a bit sceptic, because I"m not a big fan of vim "explorer" type plugins like nerd tree and similar. I already used dirvish ore netranger for quick and simple things. And I dont like to install extra stuff to complicate.

I'm a big fan of ranger, and keep using it after all these years, although there are now "faster" alternatives in C, Go, Rust etc, but nothing beats ranger extensibility.

Since I can now use my ranger knowledge and customizations "inside" neovim, I can use two things I already know and compound it's value. No need to learn new things. It's a winner !
The C-t C-x C-v mappings are very well thought. You should "advertise" them better.

No more needs for hackish solutions with tmux windows and panes.

**Comment by kevinhwang91** [comment]
Thanks for your affirmation. The motivation I create this plugin is lacking a modern file manager in Neovim like other GUI editors such as Visual Studio Code. So floating is necessary!
I usually use Ranger in the Shell env and love its high extension, so I read the source code in-depth and found it's very easy to make Ranger adapt to Neovim via RPC.
The other file explorers is only live in Neo/vim or be hard to extend like nnn, lf, and so on because they are written by static language. Although Ranger is written by Python slower than c and go, I can use some hack tech like Monkey patch to be a boss in Ranger and do whatever I want to, so the User experience is better than others.

Some code inside Ranger like vcs is slow and bad design, maybe I will override in rnvimr to get better experience, this is next plan.
