### ISSUE TITLE
Show warning if ranger isn't installed

### ISSUE THREAD

**Issue by davidv171** [kevinhwang91/rnvimr#8]
This is probably something to put on the backburner, or ignore entirely, but it would be nice if instead of the current flow of:
:RnvimrToggle displaying a floating :terminal for a literal 0.5 seconds, then disappearing without saying anything, it would display an error output.

**Comment by kevinhwang91** [comment]
Thank you for your feedback.  When I develop this plugin, showing the error messages also annoyed me so much.

In order to exit ranger process without showing `[Process exited 0]`, so I make a `TermClose` event to delete buffer after creating a floating window. Maybe I should use RPC to toggle `TermClose` event after ranger initialized without any error. 
This will make the messages staying in the floating window when the error occurs until user exit the window.
I think this idea will solve this issue.

**Comment by kevinhwang91** [comment]
I have committed the patch, please update the plugin.
You can set  `let g:rnvimr_ranger_cmd='ranger1234'` to make sure that the patch works.

Please close this issue if there are no errors.
